[package]
name = "rust-thread"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi ={version = "*", features = ["wincon", "minwindef", "consoleapi"]}
ctrlc = { version = "*", features = ["termination"] }
